"""initial schema

Revision ID: 3ed2a4537e43
Revises: 
Create Date: 2026-05-12 19:39:13.826131
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision = '3ed2a4537e43'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('banks',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('short_name', sa.String(length=128), nullable=True),
    sa.Column('swift_code', sa.String(length=32), nullable=True),
    sa.Column('country_code', sa.String(length=2), nullable=True),
    sa.Column('address_line1', sa.String(length=255), nullable=True),
    sa.Column('address_line2', sa.String(length=255), nullable=True),
    sa.Column('city', sa.String(length=128), nullable=True),
    sa.Column('postal_code', sa.String(length=32), nullable=True),
    sa.Column('website', sa.String(length=255), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('clients',
    sa.Column('first_name', sa.String(length=128), nullable=True),
    sa.Column('last_name', sa.String(length=128), nullable=True),
    sa.Column('middle_name', sa.String(length=128), nullable=True),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('personal_id_number', sa.String(length=64), nullable=True),
    sa.Column('country_code', sa.String(length=2), nullable=True),
    sa.Column('tax_residency_country_code', sa.String(length=2), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=64), nullable=True),
    sa.Column('address_line1', sa.String(length=255), nullable=True),
    sa.Column('address_line2', sa.String(length=255), nullable=True),
    sa.Column('city', sa.String(length=128), nullable=True),
    sa.Column('postal_code', sa.String(length=32), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('companies',
    sa.Column('legal_name', sa.String(length=255), nullable=False),
    sa.Column('short_name', sa.String(length=128), nullable=True),
    sa.Column('registration_number', sa.String(length=64), nullable=True),
    sa.Column('vat_number', sa.String(length=64), nullable=True),
    sa.Column('country_code', sa.String(length=2), nullable=True),
    sa.Column('address_line1', sa.String(length=255), nullable=True),
    sa.Column('address_line2', sa.String(length=255), nullable=True),
    sa.Column('city', sa.String(length=128), nullable=True),
    sa.Column('postal_code', sa.String(length=32), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('currencies',
    sa.Column('code', sa.String(length=3), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('numeric_code', sa.String(length=3), nullable=True),
    sa.Column('minor_units', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('company_bank_accounts',
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('bank_id', sa.Integer(), nullable=False),
    sa.Column('currency_code', sa.String(length=32), nullable=True),
    sa.Column('account_name', sa.String(length=255), nullable=True),
    sa.Column('iban', sa.String(length=64), nullable=True),
    sa.Column('account_number', sa.String(length=64), nullable=True),
    sa.Column('bic', sa.String(length=32), nullable=True),
    sa.Column('bank_branch', sa.String(length=255), nullable=True),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('opened_at', sa.Date(), nullable=True),
    sa.Column('closed_at', sa.Date(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['bank_id'], ['banks.id'], ),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('company_bank_accounts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_company_bank_accounts_bank_id'), ['bank_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_company_bank_accounts_company_id'), ['company_id'], unique=False)

    op.create_table('company_contacts',
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=128), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=64), nullable=True),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('company_contacts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_company_contacts_company_id'), ['company_id'], unique=False)

    op.create_table('counterparties',
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('legal_name', sa.String(length=255), nullable=False),
    sa.Column('short_name', sa.String(length=128), nullable=True),
    sa.Column('registration_number', sa.String(length=64), nullable=True),
    sa.Column('vat_number', sa.String(length=64), nullable=True),
    sa.Column('country_code', sa.String(length=2), nullable=True),
    sa.Column('address_line1', sa.String(length=255), nullable=True),
    sa.Column('address_line2', sa.String(length=255), nullable=True),
    sa.Column('city', sa.String(length=128), nullable=True),
    sa.Column('postal_code', sa.String(length=32), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=64), nullable=True),
    sa.Column('website', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('counterparties', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_counterparties_client_id'), ['client_id'], unique=False)

    op.create_table('exchange_rates',
    sa.Column('from_currency_code', sa.String(length=3), nullable=False),
    sa.Column('to_currency_code', sa.String(length=3), nullable=False),
    sa.Column('rate_date', sa.Date(), nullable=False),
    sa.Column('rate_value', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('source_name', sa.String(length=64), nullable=False),
    sa.Column('source_reference', sa.String(length=255), nullable=True),
    sa.Column('is_manual', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.CheckConstraint('from_currency_code <> to_currency_code', name='ck_exchange_rates_currency_pair_distinct'),
    sa.CheckConstraint('rate_value > 0', name='ck_exchange_rates_rate_value_positive'),
    sa.ForeignKeyConstraint(['from_currency_code'], ['currencies.code'], ),
    sa.ForeignKeyConstraint(['to_currency_code'], ['currencies.code'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('from_currency_code', 'to_currency_code', 'rate_date', 'source_name', name='uq_exchange_rates_pair_date_source')
    )
    op.create_table('ledger_accounts',
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('account_code', sa.String(length=32), nullable=False),
    sa.Column('account_name', sa.String(length=255), nullable=False),
    sa.Column('account_type', sa.Enum('asset', 'liability', 'income', 'expense', 'clearing', name='ledgeraccounttype', native_enum=False, length=16), nullable=False),
    sa.Column('purpose_code', sa.Enum('bank', 'client_settlement', 'company_commission_income', 'client_commission_expense', 'vat', 'operating_expense', 'exchange_diff', 'manual_adjustment', name='ledgeraccountpurpose', native_enum=False, length=32), nullable=False),
    sa.Column('is_system', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'account_code', name='uq_ledger_accounts_company_code')
    )
    with op.batch_alter_table('ledger_accounts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ledger_accounts_company_id'), ['company_id'], unique=False)

    op.create_table('bank_statements',
    sa.Column('company_bank_account_id', sa.Integer(), nullable=False),
    sa.Column('statement_number', sa.String(length=64), nullable=True),
    sa.Column('period_start', sa.Date(), nullable=True),
    sa.Column('period_end', sa.Date(), nullable=True),
    sa.Column('opening_balance', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('opening_balance_currency_code', sa.String(length=3), nullable=True),
    sa.Column('closing_balance', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('closing_balance_currency_code', sa.String(length=3), nullable=True),
    sa.Column('source_file_name', sa.String(length=255), nullable=True),
    sa.Column('source_file_hash', sa.String(length=128), nullable=True),
    sa.Column('imported_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['closing_balance_currency_code'], ['currencies.code'], ),
    sa.ForeignKeyConstraint(['company_bank_account_id'], ['company_bank_accounts.id'], ),
    sa.ForeignKeyConstraint(['opening_balance_currency_code'], ['currencies.code'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('bank_statements', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bank_statements_company_bank_account_id'), ['company_bank_account_id'], unique=False)

    op.create_table('company_clients',
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('responsible_contact_id', sa.Integer(), nullable=True),
    sa.Column('relationship_start_date', sa.Date(), nullable=True),
    sa.Column('relationship_end_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['responsible_contact_id'], ['company_contacts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'client_id', name='uq_company_clients_company_client')
    )
    with op.batch_alter_table('company_clients', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_company_clients_client_id'), ['client_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_company_clients_company_id'), ['company_id'], unique=False)

    op.create_table('bank_statement_lines',
    sa.Column('statement_id', sa.Integer(), nullable=False),
    sa.Column('line_number', sa.Integer(), nullable=True),
    sa.Column('booking_date', sa.Date(), nullable=True),
    sa.Column('value_date', sa.Date(), nullable=True),
    sa.Column('transaction_date', sa.Date(), nullable=True),
    sa.Column('raw_description', sa.Text(), nullable=True),
    sa.Column('raw_reference', sa.String(length=255), nullable=True),
    sa.Column('payer_name', sa.String(length=255), nullable=True),
    sa.Column('payer_account', sa.String(length=128), nullable=True),
    sa.Column('payer_bank_bic', sa.String(length=32), nullable=True),
    sa.Column('payee_name', sa.String(length=255), nullable=True),
    sa.Column('payee_account', sa.String(length=128), nullable=True),
    sa.Column('payee_bank_bic', sa.String(length=32), nullable=True),
    sa.Column('debit_amount', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('credit_amount', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('currency_code', sa.String(length=3), nullable=True),
    sa.Column('balance_after_line', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('external_transaction_id', sa.String(length=128), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['currency_code'], ['currencies.code'], ),
    sa.ForeignKeyConstraint(['statement_id'], ['bank_statements.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('bank_statement_lines', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bank_statement_lines_statement_id'), ['statement_id'], unique=False)

    op.create_table('payments',
    sa.Column('bank_statement_line_id', sa.Integer(), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('company_bank_account_id', sa.Integer(), nullable=False),
    sa.Column('related_company_id', sa.Integer(), nullable=True),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.Column('counterparty_id', sa.Integer(), nullable=True),
    sa.Column('counterparty_name', sa.String(length=255), nullable=True),
    sa.Column('payment_kind', sa.Enum('client_payment', 'expense', name='paymentkind', native_enum=False, length=32), nullable=False),
    sa.Column('payment_direction', sa.Enum('incoming', 'outgoing', name='paymentdirection', native_enum=False, length=16), nullable=False),
    sa.Column('booking_date', sa.Date(), nullable=True),
    sa.Column('value_date', sa.Date(), nullable=True),
    sa.Column('transaction_date', sa.Date(), nullable=True),
    sa.Column('amount_original', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('currency_code', sa.String(length=3), nullable=False),
    sa.Column('exchange_rate_id', sa.Integer(), nullable=True),
    sa.Column('exchange_rate_manual', sa.Numeric(precision=18, scale=8), nullable=True),
    sa.Column('amount_eur', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('payer_name', sa.String(length=255), nullable=True),
    sa.Column('payer_account', sa.String(length=128), nullable=True),
    sa.Column('payee_name', sa.String(length=255), nullable=True),
    sa.Column('payee_account', sa.String(length=128), nullable=True),
    sa.Column('payment_reference', sa.String(length=255), nullable=True),
    sa.Column('payment_purpose', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('imported', 'pending_review', 'confirmed', 'posted', 'cancelled', name='paymentstatus', native_enum=False, length=32), nullable=False),
    sa.Column('expense_category', sa.Enum('bank_fee', 'salary', 'rent', 'other', name='expensecategory', native_enum=False, length=32), nullable=True),
    sa.Column('is_manual', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.CheckConstraint("(payment_kind = 'client_payment' AND client_id IS NOT NULL) OR (payment_kind = 'expense' AND client_id IS NULL)", name='ck_payments_kind_party_consistency'),
    sa.ForeignKeyConstraint(['bank_statement_line_id'], ['bank_statement_lines.id'], ),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['company_bank_account_id'], ['company_bank_accounts.id'], ),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['counterparty_id'], ['counterparties.id'], ),
    sa.ForeignKeyConstraint(['currency_code'], ['currencies.code'], ),
    sa.ForeignKeyConstraint(['exchange_rate_id'], ['exchange_rates.id'], ),
    sa.ForeignKeyConstraint(['related_company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('bank_statement_line_id')
    )
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_payments_client_id'), ['client_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_payments_company_bank_account_id'), ['company_bank_account_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_payments_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_payments_counterparty_id'), ['counterparty_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_payments_related_company_id'), ['related_company_id'], unique=False)

    op.create_table('ledger_entries',
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('payment_id', sa.Integer(), nullable=True),
    sa.Column('entry_date', sa.Date(), nullable=False),
    sa.Column('entry_kind', sa.Enum('client_payment', 'expense', 'correction', 'opening_balance', name='ledgerentrykind', native_enum=False, length=32), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('reference_number', sa.String(length=128), nullable=True),
    sa.Column('status', sa.Enum('draft', 'confirmed', 'posted', 'cancelled', name='ledgerentrystatus', native_enum=False, length=16), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['payment_id'], ['payments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ledger_entries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ledger_entries_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ledger_entries_payment_id'), ['payment_id'], unique=False)

    op.create_table('payment_attachments',
    sa.Column('payment_id', sa.Integer(), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('content_type', sa.String(length=128), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('file_content', sa.LargeBinary(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['payment_id'], ['payments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('payment_attachments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_payment_attachments_payment_id'), ['payment_id'], unique=False)

    op.create_table('payment_financial_breakdown',
    sa.Column('payment_id', sa.Integer(), nullable=False),
    sa.Column('gross_amount_original', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('gross_amount_eur', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('vat_amount_original', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('vat_amount_eur', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('base_after_vat_original', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('base_after_vat_eur', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('company_commission_amount_original', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('company_commission_amount_eur', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('client_commission_amount_original', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('client_commission_amount_eur', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('net_client_balance_effect_eur', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.CheckConstraint('vat_amount_eur <= gross_amount_eur', name='ck_breakdown_vat_not_above_gross_eur'),
    sa.ForeignKeyConstraint(['payment_id'], ['payments.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('payment_id')
    )
    op.create_table('payment_settlement_rules_snapshot',
    sa.Column('payment_id', sa.Integer(), nullable=False),
    sa.Column('vat_applied', sa.Boolean(), nullable=True),
    sa.Column('vat_rate', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('vat_calculated_from_gross', sa.Boolean(), nullable=True),
    sa.Column('company_commission_applied', sa.Boolean(), nullable=True),
    sa.Column('company_commission_type', sa.Enum('fixed', 'percent', 'conditional', name='commissiontype', native_enum=False, length=16), nullable=True),
    sa.Column('company_commission_rate', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('company_commission_fixed_amount', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('client_commission_applied', sa.Boolean(), nullable=True),
    sa.Column('client_commission_type', sa.Enum('fixed', 'percent', 'conditional', name='commissiontype', native_enum=False, length=16), nullable=True),
    sa.Column('client_commission_rate', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('client_commission_fixed_amount', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('custom_rule_code', sa.String(length=64), nullable=True),
    sa.Column('rule_description', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['payment_id'], ['payments.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('payment_id')
    )
    op.create_table('client_balance_ledger',
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('payment_id', sa.Integer(), nullable=True),
    sa.Column('ledger_entry_id', sa.Integer(), nullable=True),
    sa.Column('entry_date', sa.Date(), nullable=False),
    sa.Column('entry_type', sa.Enum('accrual', 'payout', 'company_commission', 'client_commission', 'vat', 'correction', 'opening_balance', name='clientbalanceentrytype', native_enum=False, length=32), nullable=False),
    sa.Column('amount_eur', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['ledger_entry_id'], ['ledger_entries.id'], ),
    sa.ForeignKeyConstraint(['payment_id'], ['payments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('client_balance_ledger', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_client_balance_ledger_client_id'), ['client_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_client_balance_ledger_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_client_balance_ledger_ledger_entry_id'), ['ledger_entry_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_client_balance_ledger_payment_id'), ['payment_id'], unique=False)

    op.create_table('ledger_postings',
    sa.Column('ledger_entry_id', sa.Integer(), nullable=False),
    sa.Column('ledger_account_id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.Column('counterparty_id', sa.Integer(), nullable=True),
    sa.Column('debit_amount_eur', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('credit_amount_eur', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.CheckConstraint('(debit_amount_eur > 0 AND credit_amount_eur = 0) OR (credit_amount_eur > 0 AND debit_amount_eur = 0)', name='ck_ledger_postings_single_side_amount'),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['counterparty_id'], ['counterparties.id'], ),
    sa.ForeignKeyConstraint(['ledger_account_id'], ['ledger_accounts.id'], ),
    sa.ForeignKeyConstraint(['ledger_entry_id'], ['ledger_entries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ledger_postings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ledger_postings_client_id'), ['client_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ledger_postings_counterparty_id'), ['counterparty_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ledger_postings_ledger_account_id'), ['ledger_account_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ledger_postings_ledger_entry_id'), ['ledger_entry_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ledger_postings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ledger_postings_ledger_entry_id'))
        batch_op.drop_index(batch_op.f('ix_ledger_postings_ledger_account_id'))
        batch_op.drop_index(batch_op.f('ix_ledger_postings_counterparty_id'))
        batch_op.drop_index(batch_op.f('ix_ledger_postings_client_id'))

    op.drop_table('ledger_postings')
    with op.batch_alter_table('client_balance_ledger', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_client_balance_ledger_payment_id'))
        batch_op.drop_index(batch_op.f('ix_client_balance_ledger_ledger_entry_id'))
        batch_op.drop_index(batch_op.f('ix_client_balance_ledger_company_id'))
        batch_op.drop_index(batch_op.f('ix_client_balance_ledger_client_id'))

    op.drop_table('client_balance_ledger')
    op.drop_table('payment_settlement_rules_snapshot')
    op.drop_table('payment_financial_breakdown')
    with op.batch_alter_table('payment_attachments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payment_attachments_payment_id'))

    op.drop_table('payment_attachments')
    with op.batch_alter_table('ledger_entries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ledger_entries_payment_id'))
        batch_op.drop_index(batch_op.f('ix_ledger_entries_company_id'))

    op.drop_table('ledger_entries')
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payments_related_company_id'))
        batch_op.drop_index(batch_op.f('ix_payments_counterparty_id'))
        batch_op.drop_index(batch_op.f('ix_payments_company_id'))
        batch_op.drop_index(batch_op.f('ix_payments_company_bank_account_id'))
        batch_op.drop_index(batch_op.f('ix_payments_client_id'))

    op.drop_table('payments')
    with op.batch_alter_table('bank_statement_lines', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bank_statement_lines_statement_id'))

    op.drop_table('bank_statement_lines')
    with op.batch_alter_table('company_clients', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_company_clients_company_id'))
        batch_op.drop_index(batch_op.f('ix_company_clients_client_id'))

    op.drop_table('company_clients')
    with op.batch_alter_table('bank_statements', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bank_statements_company_bank_account_id'))

    op.drop_table('bank_statements')
    with op.batch_alter_table('ledger_accounts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ledger_accounts_company_id'))

    op.drop_table('ledger_accounts')
    op.drop_table('exchange_rates')
    with op.batch_alter_table('counterparties', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_counterparties_client_id'))

    op.drop_table('counterparties')
    with op.batch_alter_table('company_contacts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_company_contacts_company_id'))

    op.drop_table('company_contacts')
    with op.batch_alter_table('company_bank_accounts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_company_bank_accounts_company_id'))
        batch_op.drop_index(batch_op.f('ix_company_bank_accounts_bank_id'))

    op.drop_table('company_bank_accounts')
    op.drop_table('currencies')
    op.drop_table('companies')
    op.drop_table('clients')
    op.drop_table('banks')
    # ### end Alembic commands ###
